version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    env_file:
      - ./config/.env
    environment:
      - DEBUG=True
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  # For production, you might want to add:
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file:
  #     - ./config/.env.db
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
#   redis_data: 